# Generated by Django 3.0.1 on 2019-12-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_planning_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fridge_planning_core.Recipe')),
            ],
        ),
    ]
