# Generated by Django 3.0.1 on 2019-12-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge_planning_core', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
